#! /bin/bash

##
# tests
# application used for creating new tests directories
##

MIN_ARGS=1
TESTS_DIR=~/tests/

if [[ $# -lt $MIN_ARGS ]]; then
	echo "Usage:"
	echo "  $0 <action> <project_name> [ <param> ... ]"
	echo ""
	echo "Actions:"
	echo "  create -- create new project; touch specified files"
	echo "  mate   -- open specified project in textmate; no file params"
	echo "  go     -- cd to project direcotry; no params"
	echo "  list   -- list projects; takes ls params as a param"
	echo ""
fi

ACTION=$1;shift

case $ACTION in
	create )
		PROJECT_NAME=$1;shift
		mkdir ${TESTS_DIR}/$PROJECT_NAME
		for file in $@
		do
			touch ${TESTS_DIR}/$PROJECT_NAME/${file}
		done
		
		cd ${TESTS_DIR}/$PROJECT_NAME
		git init
		git add *
		git commit -m "initial import"
		;;
		
	mate )
		cd ${TESTS_DIR}/${PROJECT_NAME}
		mate .
		;;
	go )
		cd ${TESTS_DIR}/${PROJECT_NAME}
		;;
	list )
		ls $@ ${TESTS_DIR}
		;;
	* )
		echo "Unknown action: $ACTION"
		echo ""
		;;
esac
