#! /bin/bash

##
# poc builder
# application used for creating new poc directories
# 
# Spike Grobstein
# spikegrobstein@mac.com
# http://spike.grobste.in
##

MIN_ARGS=1

# check to see if POC_DIR is initialized, if not, this is the default value
if [[ -z $POC_DIR ]]; then
	POC_DIR=~/tests/
fi

# check the POC_EDITOR var to see if it was overridden or not
if [[ -z $POC_EDITOR ]]; then
	POC_EDITOR=mate
fi

# check the minimum arguments, if wrong, show usage
if [[ $# -lt $MIN_ARGS ]]; then
	echo "Usage:"
	echo "  $0 <action> <project_name> [ <param> ... ]"
	echo ""
	echo "Actions:"
	echo "  create -- create new project; touch specified files"
	echo "  edit   -- open specified project in editor. no file params"
	echo "  go     -- cd to project direcotry; no params"
	echo "  list   -- list projects; takes ls params as a param"
	echo ""
	return
fi

ACTION=$1;shift

# first check to make sure that the POC directory exists. if not, create it
if [[ ! -e $POC_DIR ]]; then
	echo "POC directory does not exist, creating ($POC_DIR)"
	echo ""
	mkdir $POC_DIR
fi

# if a project was specified, grab it and set PROJECT_NAME
if [[ $# -gt 0 ]]; then
	PROJECT_NAME=$1;shift
fi

case $ACTION in
	create )
		mkdir ${POC_DIR}/$PROJECT_NAME
		for file in $@
		do
			touch ${POC_DIR}/$PROJECT_NAME/${file}
		done
		
		cd ${POC_DIR}/$PROJECT_NAME
		git init
		git add *
		git commit -m "initial import"
		;;
		
	edit )
		cd ${POC_DIR}/${PROJECT_NAME}
		echo "cd'ing to ${POC_DIR}/${PROJECT_NAME}"
		$POC_EDITOR .
		;;
	go )
		cd ${POC_DIR}/${PROJECT_NAME}
		;;
	list )
		ls $@ ${POC_DIR}
		;;
	* )
		echo "Unknown action: $ACTION"
		echo ""
		;;
esac
