#! /bin/bash

##
# tests
# application used for creating new poc directories
##

MIN_ARGS=1
POC_DIR=~/tests/

if [[ $# -lt $MIN_ARGS ]]; then
	echo "Usage:"
	echo "  $0 <action> <project_name> [ <param> ... ]"
	echo ""
	echo "Actions:"
	echo "  create -- create new project; touch specified files"
	echo "  mate   -- open specified project in textmate; no file params"
	echo "  go     -- cd to project direcotry; no params"
	echo "  list   -- list projects; takes ls params as a param"
	echo ""
	return
fi

ACTION=$1;shift

# first check to make sure that the POC directory exists. if not, create it
if [[ ! -e $POC_DIR ]]; then
	echo "POC directory does not exist, creating ($POC_DIR)"
	echo ""
	mkdir $POC_DIR
fi

case $ACTION in
	create )
		PROJECT_NAME=$1;shift
		mkdir ${POC_DIR}/$PROJECT_NAME
		for file in $@
		do
			touch ${POC_DIR}/$PROJECT_NAME/${file}
		done
		
		cd ${POC_DIR}/$PROJECT_NAME
		git init
		git add *
		git commit -m "initial import"
		;;
		
	mate )
		cd ${POC_DIR}/${PROJECT_NAME}
		mate .
		;;
	go )
		cd ${POC_DIR}/${PROJECT_NAME}
		;;
	list )
		ls $@ ${POC_DIR}
		;;
	* )
		echo "Unknown action: $ACTION"
		echo ""
		;;
esac
